version: '3.8'

services:
  app:
    build: .
    command: sh run-app.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DJANGO_SUPERUSER_PASSWORD=123456
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  crp:
    build: ../sussa-crp
    ports:
      - 8001:8000

  nlp:
    build: ../sussa-nlp
    ports:
      - 8002:8000

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sussa_app
      - POSTGRES_USER=sussa
      - POSTGRES_PASSWORD=123456

  redis:
    image: redis:7-alpine

  celery_worker:
    build: .
    command: sh run-celery-worker.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: sh run-celery-beat.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: sh run-celery-flower.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8010:8000
    depends_on:
      - db
      - redis

  web:
    build: ../app-sussa-web-professional
    ports:
      - 80:8000
    depends_on:
      - app

volumes:
  postgres_data:
