# Generated by Django 4.1.7 on 2023-04-21 13:55

import app.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(null=True, upload_to=app.user.models.define_user_img_path),
        ),
    ]
