# Generated by Django 4.1.7 on 2023-05-01 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Email should be institutional.', regex='\\.ufal\\.br$')]),
        ),
        migrations.AlterField(
            model_name='professional',
            name='crp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='CRP code should be a sequence between 4 and 6 digits.', regex='^\\d{4,6}$')]),
        ),
    ]
