# Generated by Django 4.1.7 on 2023-05-01 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appuser_email_alter_professional_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='crp',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='CRP code should be a sequence between 4 and 6 digits.', regex='^\\d{4,6}$')]),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must have 11 digits.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must have 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
