# Generated by Django 4.1.7 on 2023-05-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
