# Generated by Django 4.1.7 on 2023-05-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='phone',
        ),
    ]
