# Generated by Django 4.1.7 on 2023-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_professional_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
