# Generated by Django 4.1.7 on 2023-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_professional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
