# Generated by Django 4.1.7 on 2023-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_destination_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('C', 'Chat'), ('I', 'Informative'), ('PH', 'Phrase'), ('AC', 'Access')], max_length=50),
        ),
    ]
