apiVersion: apps/v1
kind: Deployment
metadata:
  name: pds-2022-2-01
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pds-2022-2-01
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pds-2022-2-01
    spec:
      containers:
      - name: db
        image: postgres:13-alpine
        ports:
        - name: default-port
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: pds
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: pds
      - name: backend
        image: 716814888065.dkr.ecr.us-east-2.amazonaws.com/pds-2022-2-01:backend-main
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8000
        env:
        - name: SECRET_KEY
          value: UW7ER575bQlXVeQpZcpZs1ZuqMQooo11
        - name: DEBUG
          value: "false"
        - name: DB_NAME
          value: pds
        - name: DB_USER
          value: pds
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
---

apiVersion: v1
kind: Service
metadata:
  name: pds-2022-2-01
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: pds-2022-2-01
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
