# Generated by Django 4.1.7 on 2023-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('cta', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
