# Generated by Django 4.1.7 on 2023-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_logo',
            field=models.ImageField(null=True, upload_to='services'),
        ),
    ]
