# Generated by Django 4.1.7 on 2023-04-21 13:55

import app.service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_img_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='img_logo',
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(null=True, upload_to=app.service.models.define_service_img_path),
        ),
    ]
