# Generated by Django 4.1.7 on 2023-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='from_user',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
